### ISSUE TITLE
[Crash] Using the quest that reloads the quest book

### ISSUE THREAD

**Issue by faeldray** [cScotPlay/Primal-Skies#1]
I tried using the quest that I think it suppose to reload the quest book (there's a checkbox and it appears to reward a command block) and it crashed my game. It also appeared to glitch the quest book as clicking into any quest forces me back to the main chapter screen, so I'm unable to read quest text.

Crash report: https://pastebin.com/F8NRM8fh

**Comment by cScotPlay** [comment]
Thanks for point this out.  I appears that I created an error when trying to have this automated for the player.  The issues should be fixed with Version 0.2.1.0
