### ISSUE TITLE
Can't turn stipped Spruce log into planks

### ISSUE THREAD

**Issue by DeadlyMitten** [cScotPlay/Primal-Skies#13]
When trying to make planks, it can't be made with the stipped logs. works fine with normal logs.
Not sure if it intended or actually a bug but if it's intended I'd suggest putting it somewhere in the quests.

![image](https://user-images.githubusercontent.com/21684254/39399381-da0f8c06-4b1c-11e8-9638-11829052d73c.png)
![image](https://user-images.githubusercontent.com/21684254/39399385-fa998f44-4b1c-11e8-8245-3fb8ed363289.png)

**Comment by cScotPlay** [comment]
You do bring up a great point. Currently, the stripped logs weren't planned to be broken down an farther but it makes sense and would definitely be worth looking into for an upcoming release. Thanks for bringing this to light.
