### ISSUE TITLE
Quest Missing from book?

### ISSUE THREAD

**Issue by domosplace** [cScotPlay/Primal-Skies#17]
I do not know if this was intentional but there is a quest missing "Nether Entrance" I look through the entire book but there is no quest and all the other quest wont open up in the first tab because of this.

**Comment by cScotPlay** [comment]
I need to check but the quest you are looking for falls in the botania tab you will need to work through a portion of botania to get a nether portal.

**Comment by domosplace** [comment]
Thank you for getting to me so quickly. I am working on it now I will see what happens and let you know.

**Comment by cScotPlay** [comment]
Glad it worked out.  Hope that getting to the nether is fruitful for you.
