### ISSUE TITLE
JEI Search Crashes

### ISSUE THREAD

**Issue by Airelda** [cScotPlay/Primal-Skies#18]
My game crashed when I searched for fl (flint) and ax (axe). I am sure there is more but I stopped playing it until jei is fixed.

**Comment by cScotPlay** [comment]
Airelda,
A couple of questions for you.
-What version are you currently playing on?
-Did you get a crash report with crash and if so could you post it also?

Thanks for bring this to our attention.

**Comment by Airelda** [comment]
I was playing v. 1.0.8

**Comment by cScotPlay** [comment]
Were you able to get a crash report from the incident?
