### ISSUE TITLE
Server RockHounding

### ISSUE THREAD

**Issue by Ctfurlani** [cScotPlay/Primal-Skies#19]
Hi, for some reason the server does not work in the lab oven. I tried in the mineral sizer and it was fine, but not in the lab oven. Also, the input and output fluid system don't drop after they are broken with a pick. Appreciate the attention.

**Comment by kiwifrogg** [comment]
You are about the only person that has used the servers :) most can't work out how they work gg :). As for the fluid drop issue is a known one, but was meant to be fixed in the current version, but it might pay to report both these to the rockhounding issue tracker, so he knows the issue is still there. https://github.com/GlobbyPotato/Rockhounding_Chemistry/issues

**Comment by Ctfurlani** [comment]
That's a bummer, it's really hard to automate the process of making osmium without setting multiple lab ovens. But thanks for the feedback

**Comment by kiwifrogg** [comment]
The RH dev is really fast onto issues, so if you report it he'll probably fix it in a few hours :)

**Comment by cScotPlay** [comment]
We are working on updated the entire pack to a newer version of forge.  Hopefully this will help with a couple of the issues you are running into.

**Comment by Ctfurlani** [comment]
Hello again hahah, I just updated the pack to 1.0.9 and I'm having trouble loading the game. Here is what is shown:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Guidebook (gbook)
Sorry to bother again

**Comment by cScotPlay** [comment]
Yes know issue that we are a bit embarrassed about. So when updating the Guidebook model to help with visibility of one of the most important guides in the game we ran across this issue. Forge is now placing core mods are being dealt with differently now. The current version of Guidebooks accounts for this but the version of Forge we are using does not. Therefore, we are working complete update with a newer and recommend version of Forge. This should fix a majority of issues. We are finalizing checking to make sure everything transferred over and no major issues are present. We hope to have it posted to curse here in the next couple 9f hours. In the meantime, please roll back to version 1.0.8.

**Comment by Ctfurlani** [comment]
Got it. Thanks

**Comment by cScotPlay** [comment]
The pack is updated and on the Curse.
