### ISSUE TITLE
Crash while loading

### ISSUE THREAD

**Issue by mansrm81** [cScotPlay/Primal-Skies#20]
Hello I'm getting a crash that points to the guidebook on the latest version of this pack.

Here is a link to the crash report below.
https://pastebin.com/dGeZeaK5

**Comment by mansrm81** [comment]
NVM it's a known issue that will be fixed in a new version of the pack.

**Comment by cScotPlay** [comment]
Updated pack is approved on Curse now.  It should fix all the issues with loading
