### ISSUE TITLE
Mana tools

### ISSUE THREAD

**Issue by Ctfurlani** [cScotPlay/Primal-Skies#21]
Hello, the manasteel axe and the elementium axe disappear after making sticks, same with the steel axe from kitsu's.

**Comment by cScotPlay** [comment]
Ok thanks for letting us know we will get an update pushed with this fix. Thanks again

**Comment by Ctfurlani** [comment]
No problem. Also, I think the tar recipe in the retention vat is not working. Could not insert catalysts in the lab oven as well.

**Comment by cScotPlay** [comment]
Removed ability to craft sticks with Botania tools due to issues of Craftweaker not allowing this in the current configuration.
