### ISSUE TITLE
Tar Recipe not working

### ISSUE THREAD

**Issue by Rue82** [cScotPlay/Primal-Skies#22]
Noticed on last update version 1.1.2 Tar recipe in retention vat is broken. It now gives you some rockhounding minerals but not Tar.  Tried multiple different flotations with no success.  The flotation in JEI is 3.18.

**Comment by Rue82** [comment]
Also the crushed black quartz to quartz in the Leaching Vat is not working either.  Recipe shows up and says it should work but does not start.

**Comment by cScotPlay** [comment]
Fixed in version 1.1.3
