### ISSUE TITLE
Wrought Iron Recipe Returing Vanilla Iron Ore

### ISSUE THREAD

**Issue by elder-sign** [cScotPlay/Primal-Skies#23]
Pack Version 1.1.2 

Pulverized iron foes into the crucibles just fine, they heat up in the bloomery as expected, however after placing them in world and breaking them to get the wrought iron the block drops an empty crucible and a piece of vanilla iron ore.

**Comment by cScotPlay** [comment]
We are tracking this issue and are awaiting updates from Kitsu's ForgeCraft.  It's not really game breaking so we have let it go.

**Comment by elder-sign** [comment]
The only thing that it breaks is the quest book, and slows down iron production to 1/9...

**Comment by cScotPlay** [comment]
If you are getting Vanilla Iron Ore back you are doing something wrong.  Either the temperature is too high in your bloomery or you are pulling the Crucible out to early.  Both of these things will result in a crafted or broken  crucible.  The known issue is when you break the cracked/broke crucible.  Make sure that you are doing the process entirely and the proper way to keep from getting this happening.

**Comment by elder-sign** [comment]
Most likely pulling it out too early, the crucible seems to glow almost instantaneously, maybe 40 ticks at most, but I'd have to assume that if the crucible was cracked or broken then it wouldn't drop the crucible itself when broke open, all in all pretty strange

**Comment by Rue82** [comment]
What did the timer say for ticks remaining?  The graphic has nothing to do with the actual crafting. And yes just because something is hot does not mean that what is in it is complete.

**Comment by elder-sign** [comment]
ticks remaining read as 0
