### ISSUE TITLE
Mobs not dropping ore dusts in mob farm

### ISSUE THREAD

**Issue by kamyflouge** [cScotPlay/Primal-Skies#24]
I’m not really sure if it's intended or not but after making a mob farm where mobs get pushed with cineris carpet and fall into pitfall spikes. I realize I didn’t get any of the ore dusts. I’d really appreciate it if it wasn’t limited to player kills. Thanks

**Comment by cScotPlay** [comment]
This was a calculated decision and we went round and round about it but determined that we wanted the mob drops to only work from player kills to require further progression through other ways of obtaining resources.

**Comment by kamyflouge** [comment]
Thanks for the reply. I guess I could make a player kill mob farm . But is the botania ore gen the next thing? Cause I don’t really know what’s next

**Comment by cScotPlay** [comment]
Yes, that is the next portion of ore generation.  There are three or four options.  You have Bontania, Actually Additions, Mining the Nether, and Mekanism when you get there.
