### ISSUE TITLE
Creation of thatch?

### ISSUE THREAD

**Issue by Tokeli** [cScotPlay/Primal-Skies#26]
Thatch is needed for adobe bricks, but in 1.1.4 there is no clear way to create it? Fresh Thatching can be created with grass, rush tips, or rush stems- none of which can be created or gathered.

**Comment by cScotPlay** [comment]
Typically you add the wet thatch to the PrimalCore Drying Rack to get the dried thatch. I wasn't aware of it not working in 1.1.4 but give me a bit to see if it is indeed not working properly.

**Comment by Tokeli** [comment]
It took watching a Lets Play of the modpack for me to realize that you just have to bonemeal grass blocks to get grass on top of them, to use to make the thatch. Woops. Sorry about that.
