### ISSUE TITLE
Bug Item disappearing 

### ISSUE THREAD

**Issue by ghost** [cScotPlay/Primal-Skies#31]
I just starting playing this modpack I crafted a flint saw and it disapeared when I was crafting and it wasnt broken or something ... The bug happened with the spruce crafting table ! it was on multiplayer

**Comment by cScotPlay** [comment]
I can't seem to get this to replicate.  This is what I am expecting you were doing.
Used PrimalCore Spruce Crafting Table -> Crafted 2 Flaked Flint, 1 Plant Twine, and 1 Stick together.  
I tried shift-clicking it out and pulling it without shift-clicking.  Is there anything special you did when crafting this?  One other question, were you on a server in multiplayer?  If so, what server were you on? (If you don't mind me asking)

**Comment by ghost** [comment]
yes it was in multiplayer

**Comment by cScotPlay** [comment]
Ok.  This could be a bunch of things but there are a couple of things to look at.  The flint saw does not require a 3x3 crafting grid (not that this should matter) try crafting it in your personal 2x2 crafting grid and see if it does the same thing.  The only other thing that I can think it would be is a crappy case of server lag that just ate the tool.  I've never seen this happen but there are somethings with server ticks and other things that go weird.
