### ISSUE TITLE
Quest Book quests disappeared

### ISSUE THREAD

**Issue by Thundernado** [cScotPlay/Primal-Skies#32]
(My first time on GitHub)
The pack was perfect. So I decided to add an texture pack (NearlyDefault) but when my world's opens, the quests in the quest book are gone, also the thumbnail, alwais in the questbook gone, please help **:/**

**Comment by cScotPlay** [comment]
I have been unable to completely emulate your exact issues but here is a couple of things that I think may be going on.  First, I was able to load the NearlyDefault resource pack (wow looks pretty nice) and it loads fine.  The thumbnail for the questbook is located at the following location Folder: resources\ps\textures\gui\bq_menu_title.png.  If that structure or file is no longer there then it will not show up properly.  My guess is that something happened with this folder when you were installing the resource pack.  As for the actual quests, if your not playing on a server try reloading the questbook via "/bq_admin default load" command.  It may not bring back in your current progress but that can be fixed.  If niether of those options work it might require you to downgrade the pack and then upgrade it back to the current version.  This will hopefully save your current progress in your world with out having to delete the instance and start over.

**Comment by Thundernado** [comment]
All my completed quests are gone, the thumbnail and the quest are returned🎉🎊👌🏿.Yay x2
