### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Thundernado** [cScotPlay/Primal-Skies#33]
Here's the crash report:[crash-2018-10-14_16.50.19-client.txt](https://github.com/cScotPlay/Primal-Skies/files/2476519/crash-2018-10-14_16.50.19-client.txt).
I don't know what happening today at this pack...
But i need help... I don't think that a textures pack can make eveything bug...

**Comment by cScotPlay** [comment]
Downgrade Forge to version 14.23.4.2705.  This is the version the pack was developed on and is the most stable.

**Comment by Thundernado** [comment]
> Downgrade Forge to version 14.23.4.2705. This is the version the pack was developed on and is the most stable.

I can’t find it in the Twitch forge’s version. The most recent version is 14.23.4.2700

**Comment by cScotPlay** [comment]
Go to the Twitch Launcher and click on the instance of Primal Skies it will bring you to a screen that looks like this.
![image](https://user-images.githubusercontent.com/33098040/46949756-20202380-d048-11e8-94ae-8718246a2e99.png)

Then click the button with the "..." in the uppter right hand corner and select profile options.
![image](https://user-images.githubusercontent.com/33098040/46949829-5b225700-d048-11e8-97e3-b595449b2446.png)

Then open up the drop down box for "Current ModLoader Version" and navigate to the version that ends in 2705
![image](https://user-images.githubusercontent.com/33098040/46949901-8e64e600-d048-11e8-9e5a-b3fe44d3716b.png)

**Comment by Thundernado** [comment]
Oh yes.... I was  mistaking🤦🏿‍♂️. Thanks everything works now, Yay🎮
