### ISSUE TITLE
Game crashes all the time

### ISSUE THREAD

**Issue by AkArli74u** [cScotPlay/Primal-Skies#38]
The game always crashes it loads everything perfectly then when I go to play or create a single player world it crashes. All it says is “An unexpected issue occurred and the game has crashed. We’re sorry for the inconvenience.” It doesn’t give me any crash reports and I don’t have the best pc but I’ve played modpacks with more mods Just posted this on curse to but saw to post here instead

**Comment by cScotPlay** [comment]
Sorry that I am just getting back with you.  There have been other users that had the same problem.  For them it was an issue with a newer version of Java.  Others have had an issue where the file was located.  Check and see if this link helps any. https://support.feed-the-beast.com/t/codechicken-lib-is-crashing-my-game/34918/5
