### ISSUE TITLE
Exoflame + Foundry = crash

### ISSUE THREAD

**Issue by meradudd** [cScotPlay/Primal-Skies#39]
Placed an exoflame down to try and power my four foundry burner heaters ( cause, why not, right?).  Crashed hard and world won't reload.  Crash log below.

[crash-2018-11-24_00.03.36-server.txt](https://github.com/cScotPlay/Primal-Skies/files/2613155/crash-2018-11-24_00.03.36-server.txt)

**Comment by cScotPlay** [comment]
Alrighty.  Let me see what we can do.

**Comment by cScotPlay** [comment]
This issue was fixed in recent versions of Foundry.  Updated Foundry mod in **version 1.1.12**.  In testing, the Exoflame will work on the Alloy Furnace but I was unable to get the Burner Heaters to recognize the Exoflame.

**Comment by meradudd** [comment]
Yah....it seems to be a 'dead end' now.  Ah well.  Thanks for the quick response.

**Comment by cScotPlay** [comment]
Botania is coded so that the Exoflame looks for furnace type elements.  I don't think that the Burner Heater inherits the furnace class.  Therefore, its probably not going to work.  As for the Alloyfurance, it should work no problems.
