### ISSUE TITLE
Stuck on Petal Apothecary and the Stone Tongs/Soft Crucible quests.  How can I force complete these?

### ISSUE THREAD

**Issue by kurtu5** [cScotPlay/Primal-Skies#4]
I am stuck on the Petal Apothecary and the Stone Tongs/Soft Crucible quests.

In other mod packs with BQM, when you get stuck on a quest you can hold shift while mousing over a quest and see it's number.  Then you can go into cheat mode and issue /bq_admin complete <quest_number>.   But the shift and mouse over doesn't show a quest number.  Any ideas how to get that functioning?

**Comment by jdiveley** [comment]
I ran into the same issue but was able to locate the ID's in config/Betterquesting/Defaultquests.json

Petal Apothecary: ID 29
Tools of the  Trade:  ID 24

**Comment by cScotPlay** [comment]
By just hovering over the quest does it show you the information regarding the quest, i.e. Quest Name and previously required quest?  If so then the number is on the first line right after the quest title.  I think that is you use F3 & H to show advanced tooltips it will show you this information.

Tools of the Trade = 24
Fower Altar = 29

Just out of curiosity did you craft these items in the in the Primal Crafting Table?

**Comment by kurtu5** [comment]
Very odd.  So I recrafted the items a few hours ago in the vanilla table.  And they didn't detect.   And in response to your question, I cheated in the materials, exited an re-entered into SMP with no cheats and tried the vanilla crafting table and then the primal table and still didn't detect.  I then went to the reset quest, and then was able to craft them both in a vanilla table and they detected.

BQM.   You are so nice and your detect button is garbage.  :P 
Oh and I didn't know the advanced tool tips is what allowed me to hover and see the quest number.   That will come in handy.  Of course, I will report buggy quests to you and test them as I come across them before cheating them done.

**Comment by cScotPlay** [comment]
Well, I know that BQM and PrimalCore items do not play nice with it comes to shift clicking crafted items out.  I am currently reworking the quest as we speak to account for this and not require a vanilla crafting table just for questing.

**Comment by kurtu5** [comment]
Ah yes that detail.  I forgot to mention that I was careful to not shiftclick the completed item out on the subsequent attempts.

**Comment by cScotPlay** [comment]
Version 0.2.2.0 should fix the majority of Quest issues.  Changed all Crafting Quest for Retrieval Quest.
