### ISSUE TITLE
Xnet controller losing all connections

### ISSUE THREAD

**Issue by meradudd** [cScotPlay/Primal-Skies#40]
So, I set up a network with Xnet to automate crystallized canola production and ore production with 6 channels, 5 advanced connectors and 5 connectors total.  Runs great but after several hours, Xnet loses it's mind - literally.  All of the connections are lost by the controller.  The original channels are still there, but the connections are missing.  One by one, I broke/reset the connectors (starting with the controller), but ended up having to also reset the the cabling.  Since resetting the connectors means new connections, the programming is also lost.

This has happened twice in the last 24 hr.  Help?

**Comment by cScotPlay** [comment]
This appeared to be an issue with XNet losing ownership of rights in the controllers.  Updated XNet in hopes of solving this issue in version 1.1.12.

**Comment by meradudd** [comment]
Xnet appears to be in it's right mind now.  Thanks ever so much for the fix and especially the quick response.
