### ISSUE TITLE
 I can not enter the game!

### ISSUE THREAD

**Issue by Drimyr** [cScotPlay/Primal-Skies#45]
the game crashes every time you try to enter the single world because of an unknown error and does not issue any reports. I used to play (even on a weaker PC), I am a Russian user and I write through a translator. Can you please tell me what can I do to fix the game?

**Comment by cScotPlay** [comment]
Is it possible for you to post the debug.log file that is found in the log folder? This may show us where the error is. Thanks.

**Comment by Drimyr** [comment]
I found in the log only one file with the name "crash-2019-01-22_22.55.30-server" and it is absolutely empty. Tell me, maybe I'm not looking there?

**Comment by Drimyr** [comment]
I hope this will help https://paste.feed-the-beast.com/view/f27d6822

**Comment by mtbrenner** [comment]
Memory: 760223776 bytes (725 MB) / 1141374976 bytes (1088 MB) up to 2863661056 bytes (2731 MB)
JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m

This looks a bit low on memory. You have 3GB allocated to Minecraft. The log from my PC says

Memory: 696301232 bytes (664 MB) / 824180736 bytes (786 MB) up to 3817865216 bytes (3641 MB)
JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m

And these 4GB are already low. Do you have enough RAM to give Minecraft at least 4GB?

**Comment by Drimyr** [comment]
Yes, enough. I tried to allocate different volumes of memory, but nothing has changed. Now selected 4

**Comment by cScotPlay** [comment]
Simple solution.  Either remove Optifine or roll it back the E2 version.  E3 was crashing my system out also.  RAM didn't see to be an issue as I ran it on 3gigs also.  Hope this helps

**Comment by Drimyr** [comment]
Thank you so much, it helped, I can finally return to my favorite game. Thanks for the help

**Comment by cScotPlay** [comment]
Glad that helped.  It confused me for quite a bit initially.
