### ISSUE TITLE
Quest book

### ISSUE THREAD

**Issue by Drimyr** [cScotPlay/Primal-Skies#46]
Hello, I have a problem with the book of quests. All completed quests are closed again, tell me how to fix this?

**Comment by cScotPlay** [comment]
Can you provide a couple of screenshots to help identify the problem?

**Comment by Drimyr** [comment]
![2019-03-02_20 01 29](https://user-images.githubusercontent.com/46929076/53681568-6be91600-3d26-11e9-8d7d-17ade137371a.png)

**Comment by Drimyr** [comment]
![2019-03-02_20 01 50](https://user-images.githubusercontent.com/46929076/53681581-920eb600-3d26-11e9-8815-6e9f2cb0b380.png)

**Comment by Drimyr** [comment]
![2019-03-02_20 01 34](https://user-images.githubusercontent.com/46929076/53681587-9d61e180-3d26-11e9-9748-26bb5665bb23.png)

**Comment by cScotPlay** [comment]
You may need to go into bq_admin edit and complete the quest you already completed. Good thing there weren't any rewards so you dont need to worry about getting double the stuff.
