### ISSUE TITLE
"STeel Galdius" doesn't detect in "Everyday Tools" quest.

### ISSUE THREAD

**Issue by kurtu5** [cScotPlay/Primal-Skies#8]
Every tools but the steel gladius detects in this quest. 

Version 0.2.2.2.Beta
 
![2018-04-02_03 09 14](https://user-images.githubusercontent.com/3052634/38186890-41b1e458-3623-11e8-94ca-1af50afb78e1.png)

![2018-04-02_03 07 58](https://user-images.githubusercontent.com/3052634/38186863-1b961140-3623-11e8-9871-7a9c79f68071.png)

**Comment by cScotPlay** [comment]
Thank you.  That needs to be adjusted from a crafting to retrieval quest.  Thank you for point this out.

**Comment by cScotPlay** [comment]
Fixed in version 0.3.0.0
